use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum UiLanguage {
    En,
    #[default]
    ZhCn,
    ZhTw,
    Ja,
}

impl UiLanguage {
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::En => "en",
            Self::ZhCn => "zh-CN",
            Self::ZhTw => "zh-TW",
            Self::Ja => "ja",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "en" | "english" => Some(Self::En),
            "zh-cn" | "zh_cn" | "zh-hans" | "简体中文" => Some(Self::ZhCn),
            "zh-tw" | "zh_tw" | "zh-hant" | "繁體中文" | "繁体中文" => Some(Self::ZhTw),
            "ja" | "jp" | "japanese" | "日本語" => Some(Self::Ja),
            _ => None,
        }
    }

    #[must_use]
    pub const fn pack(self) -> &'static LanguagePack {
        match self {
            Self::En => &EN,
            Self::ZhCn => &ZH_CN,
            Self::ZhTw => &ZH_TW,
            Self::Ja => &JA,
        }
    }
}

pub struct LanguagePack {
    pub activity: &'static str,
    pub input: &'static str,
    pub setup: &'static str,
    pub setup_cancel_hint: &'static str,
    pub command_palette: &'static str,
    pub command_hint: &'static str,
    pub editor_hint: &'static str,
    pub onboarding_title: &'static str,
    pub onboarding_step_provider: &'static str,
    pub onboarding_step_commands: &'static str,
    pub model_unconfigured: &'static str,
    pub configured_language: &'static str,
    pub cancelled: &'static str,
    pub provider_add_title: &'static str,
    pub provider_name_prompt: &'static str,
    pub provider_protocol_prompt: &'static str,
    pub provider_protocol_responses: &'static str,
    pub provider_protocol_chat: &'static str,
    pub provider_protocol_messages: &'static str,
    pub provider_url_prompt: &'static str,
    pub provider_switch_prompt: &'static str,
    pub provider_key_update_prompt: &'static str,
    pub provider_key_updated: &'static str,
    pub provider_key_rollback: &'static str,
    pub provider_default_prompt: &'static str,
    pub vector_setup_title: &'static str,
    pub vector_setup_description: &'static str,
    pub vector_provider_prompt: &'static str,
    pub vector_custom_name_prompt: &'static str,
    pub vector_url_prompt: &'static str,
    pub vector_model_prompt: &'static str,
    pub vector_models_prompt: &'static str,
    pub vector_model_select_prompt: &'static str,
    pub vector_voyage_option: &'static str,
    pub vector_jina_option: &'static str,
    pub vector_custom_option: &'static str,
    pub vector_model_verified: &'static str,
    pub vector_model_verify_on_select: &'static str,
    pub vector_enabled: &'static str,
    pub global_configuration: &'static str,
    pub vector_dimensions_prompt: &'static str,
    pub vector_dimensions_fallback: &'static str,
    pub secure_key_prompt: &'static str,
    pub select_confirm: &'static str,
    pub first_model_hint: &'static str,
    pub default_model_label: &'static str,
    pub model_ready: &'static str,
    pub connect_first: &'static str,
    pub choose_as_default: &'static str,
    pub remove_provider_hint: &'static str,
    pub session_label: &'static str,
    pub goal_label: &'static str,
    pub model_label: &'static str,
    pub reasoning_label: &'static str,
    pub limits_label: &'static str,
    pub capability_label: &'static str,
    pub mode_label: &'static str,
    pub context_label: &'static str,
    pub cache_label: &'static str,
    pub prompt_cache_label: &'static str,
    pub agents_label: &'static str,
    pub provider_switched: &'static str,
    pub provider_verified: &'static str,
    pub models_fetched: &'static str,
    pub vector_verified: &'static str,
    pub dimensions_label: &'static str,
    pub vector_saved_restart: &'static str,
    pub vector_key_saved: &'static str,
    pub ready_label: &'static str,
    pub working_label: &'static str,
    pub secure_label: &'static str,
    pub composer_placeholder: &'static str,
    pub send_hint: &'static str,
    pub scroll_hint: &'static str,
    pub you_label: &'static str,
    pub add_provider_action: &'static str,
    pub connect_provider_action: &'static str,
    pub browse_commands_action: &'static str,
    pub exit_hint: &'static str,
    pub vector_label: &'static str,
    pub vector_configured_label: &'static str,
    pub vector_unconfigured_label: &'static str,
    pub vector_ready_label: &'static str,
    pub vector_active_label: &'static str,
    pub vector_degraded_label: &'static str,
    pub vector_setup_action: &'static str,
    pub new_session_title: &'static str,
    pub agent_md_action: &'static str,
    pub permission_label: &'static str,
    pub sandbox_label: &'static str,
    pub permission_cycle_hint: &'static str,
}

pub(crate) fn command_description(
    language: UiLanguage,
    name: &str,
    zh_cn: &'static str,
) -> &'static str {
    if language == UiLanguage::ZhCn {
        return zh_cn;
    }
    let (en, zh_tw, ja) = match name {
        "/account" => (
            "Show account metadata without secrets",
            "顯示不含密鑰的帳戶中繼資料",
            "秘密を含まないアカウント情報を表示します",
        ),
        "/agent" => (
            "Inspect one agent's role, capabilities, and lifecycle",
            "檢視單一 Agent 的角色、能力與生命週期",
            "単一エージェントの役割・能力・状態を確認します",
        ),
        "/agentmd" => (
            "Manage global or project-private agent.md instructions",
            "管理全域或專案私有的 agent.md 指令",
            "グローバルまたはプロジェクト専用の agent.md 指示を管理します",
        ),
        "/agents" => (
            "List agents using normal, verbose, compact, or tree views",
            "以標準、詳細、精簡或樹狀模式列出 Agent",
            "エージェントを標準・詳細・簡潔・ツリー表示します",
        ),
        "/approve" => (
            "Approve a waiting tool invocation",
            "核准等待中的工具呼叫",
            "待機中のツール実行を承認します",
        ),
        "/browser" => (
            "Control the isolated browser runtime",
            "控制隔離的瀏覽器執行環境",
            "分離されたブラウザー実行環境を操作します",
        ),
        "/budget" => (
            "Inspect or change agent execution budgets",
            "檢視或調整 Agent 執行預算",
            "エージェント実行予算を確認・変更します",
        ),
        "/cache" => (
            "Show L1/L2 cache metrics",
            "顯示 L1/L2 快取指標",
            "L1/L2 キャッシュの指標を表示します",
        ),
        "/checkpoint" => (
            "Create a durable context checkpoint",
            "建立可持久化的 Context 檢查點",
            "永続コンテキストのチェックポイントを作成します",
        ),
        "/clear" => (
            "Clear the terminal viewport only",
            "只清除終端顯示內容",
            "端末の表示領域だけを消去します",
        ),
        "/compact" => (
            "Checkpoint and compact context safely",
            "建立檢查點並安全壓縮 Context",
            "チェックポイント後にコンテキストを安全に圧縮します",
        ),
        "/config" => (
            "Show effective layered configuration and provenance",
            "顯示有效分層設定與來源",
            "有効な階層設定と由来を表示します",
        ),
        "/connect" => (
            "Securely connect a built-in model provider",
            "安全連接內建模型提供商",
            "組み込みモデルプロバイダーへ安全に接続します",
        ),
        "/context" => (
            "Inspect context series, budget, filters, and checkpoints",
            "檢視 Context 系列、預算、篩選與檢查點",
            "コンテキスト系列・予算・フィルター・チェックポイントを確認します",
        ),
        "/debug" => (
            "Show a read-only runtime debug snapshot",
            "顯示唯讀執行階段除錯快照",
            "読み取り専用の実行時デバッグ情報を表示します",
        ),
        "/deny" => (
            "Deny a waiting tool invocation",
            "拒絕等待中的工具呼叫",
            "待機中のツール実行を拒否します",
        ),
        "/diff" => (
            "Show the current Git diff",
            "顯示目前 Git 差異",
            "現在の Git 差分を表示します",
        ),
        "/doctor" => (
            "Run read-only runtime diagnostics",
            "執行唯讀執行階段診斷",
            "読み取り専用の実行時診断を行います",
        ),
        "/exit" => (
            "Save state and exit",
            "儲存狀態並離開",
            "状態を保存して終了します",
        ),
        "/failover" => (
            "Manage explicit cost-confirmed model failover",
            "管理需確認成本的明確模型容錯切換",
            "費用確認付きの明示的モデル切替を管理します",
        ),
        "/focus" => (
            "Set or clear the durable retrieval focus",
            "設定或清除持久化檢索焦點",
            "永続検索フォーカスを設定・解除します",
        ),
        "/forget" => (
            "Delete one project-memory record",
            "刪除一筆專案記憶",
            "プロジェクトメモリを1件削除します",
        ),
        "/fork" => (
            "Fork a child session from a checkpoint",
            "從檢查點分支子 Session",
            "チェックポイントから子セッションを分岐します",
        ),
        "/git" => (
            "Run allowlisted read-only Git operations",
            "執行允許清單內的唯讀 Git 操作",
            "許可済みの読み取り専用 Git 操作を行います",
        ),
        "/goal" => (
            "View and manage the durable goal",
            "檢視與管理持久化 Goal",
            "永続ゴールを表示・管理します",
        ),
        "/help" => (
            "Show command help",
            "顯示命令說明",
            "コマンドのヘルプを表示します",
        ),
        "/index" => (
            "Build, update, inspect, or search the repository index",
            "建立、更新、檢視或搜尋 Repository Index",
            "リポジトリ索引を構築・更新・確認・検索します",
        ),
        "/inspect" => (
            "Inspect one harness subsystem",
            "檢視單一 Harness 子系統",
            "Harness のサブシステムを1つ確認します",
        ),
        "/language" => (
            "Switch the customized terminal language pack",
            "切換高度客製化的終端語言包",
            "専用に調整された端末言語パックを切り替えます",
        ),
        "/logout" => (
            "Remove a provider credential from the OS store",
            "從作業系統憑證庫移除 Provider 憑證",
            "OS 資格情報ストアからプロバイダー認証を削除します",
        ),
        "/logs" => (
            "Show recent redacted runtime events",
            "顯示近期已遮蔽的執行階段事件",
            "秘匿化された最近の実行イベントを表示します",
        ),
        "/lsp" => (
            "Query LSP and manage safe edit previews",
            "查詢 LSP 並管理安全編輯預覽",
            "LSP の照会と安全な編集プレビューを管理します",
        ),
        "/mcp" => (
            "Manage lazy MCP servers and their capabilities",
            "管理惰性 MCP Server 與能力",
            "遅延起動の MCP サーバーと機能を管理します",
        ),
        "/memory" => (
            "Manage structured project memory and retrieval",
            "管理結構化專案記憶與檢索",
            "構造化プロジェクトメモリと検索を管理します",
        ),
        "/mode" => (
            "Switch the real runtime resource profile",
            "切換實際執行資源模式",
            "実際の実行リソースプロファイルを切り替えます",
        ),
        "/model" => (
            "Switch the model within the current provider",
            "切換目前提供商內的模型",
            "現在のプロバイダー内でモデルを切り替えます",
        ),
        "/models" => (
            "List models or explicitly refresh one provider catalog",
            "列出模型或明確更新單一提供商目錄",
            "モデル一覧または単一プロバイダーの明示更新を行います",
        ),
        "/patch" => (
            "List durable patch records",
            "列出持久化 Patch 記錄",
            "永続パッチ記録を一覧表示します",
        ),
        "/permissions" => (
            "Manage manual, edit, auto, full, bypass modes and durable rules",
            "管理手動、編輯、自動、完整、bypass 模式與持久規則",
            "手動・編集・自動・フル・bypass モードと永続ルールを管理します",
        ),
        "/pin" => (
            "Add context that compaction cannot remove",
            "加入不會被壓縮移除的 Context",
            "圧縮で削除されないコンテキストを追加します",
        ),
        "/plan" => (
            "Show the current task plan",
            "顯示目前任務計畫",
            "現在のタスク計画を表示します",
        ),
        "/plugins" => (
            "Review and manage isolated plugins",
            "審查並管理隔離 Plugin",
            "分離プラグインを審査・管理します",
        ),
        "/profile" => (
            "Show measured runtime latency profiles",
            "顯示實測執行延遲分析",
            "実測された実行レイテンシを表示します",
        ),
        "/provider" => (
            "Show, add, switch, re-key, or remove text-model providers",
            "顯示、新增、切換、更新 Key 或刪除文字模型提供商",
            "テキストモデルのプロバイダーを表示・追加・切替・キー更新・削除します",
        ),
        "/providers" => (
            "List provider routes and credential readiness",
            "列出提供商路由與憑證狀態",
            "プロバイダーの経路と認証状態を一覧表示します",
        ),
        "/queue" => (
            "Inspect, cancel, or reprioritize queued work",
            "檢視、取消或調整排程工作優先度",
            "待機作業を確認・取消・優先度変更します",
        ),
        "/reasoning" => (
            "Set model reasoning effort with visible clamping",
            "設定模型推理強度並顯示能力限制",
            "モデルの推論強度を設定し制限結果を表示します",
        ),
        "/reset" => (
            "Checkpoint then reset nonessential context",
            "建立檢查點後重設非必要 Context",
            "チェックポイント後に不要なコンテキストをリセットします",
        ),
        "/resume" => (
            "Resume a recoverable agent team",
            "恢復可復原的 Agent Team",
            "復旧可能なエージェントチームを再開します",
        ),
        "/retry" => (
            "Retry a safe failed tool invocation",
            "重試可安全重複的失敗工具",
            "安全に再試行できる失敗ツールを再実行します",
        ),
        "/review" => (
            "Run a controlled code review",
            "執行受控程式碼審查",
            "制御されたコードレビューを実行します",
        ),
        "/rollback" => (
            "Restore context from a checkpoint into a new series",
            "從檢查點還原為新的 Context 系列",
            "チェックポイントから新しいコンテキスト系列へ復元します",
        ),
        "/sandbox" => (
            "Inspect or switch OS-enforced sandbox and network boundaries",
            "檢視或切換作業系統強制的 Sandbox 與網路邊界",
            "OS が強制するサンドボックスとネットワーク境界を確認・切替します",
        ),
        "/session" => (
            "Pick, create, switch, or rename a project-local session",
            "選擇、建立、切換或重新命名專案本機 Session",
            "プロジェクト内のセッションを選択・作成・切替・改名します",
        ),
        "/sessions" => (
            "List project sessions and fork lineage",
            "列出專案 Session 與分支關係",
            "プロジェクトのセッションと分岐関係を一覧表示します",
        ),
        "/settings" => (
            "Inspect or change session/runtime settings",
            "檢視或調整 Session/Runtime 設定",
            "セッション／実行時設定を確認・変更します",
        ),
        "/skills" => (
            "Search and lazily load skills",
            "搜尋並惰性載入 Skill",
            "スキルを検索して遅延読み込みします",
        ),
        "/status" => (
            "Show model, mode, goal, and session status",
            "顯示模型、模式、Goal 與 Session 狀態",
            "モデル・モード・ゴール・セッション状態を表示します",
        ),
        "/steer" => (
            "Send guidance to an active supervisor",
            "向執行中的 Supervisor 傳送指引",
            "実行中のスーパーバイザーへ指示を送ります",
        ),
        "/team" => (
            "Inspect or start research, compact, or capability-routed adaptive evidence teams",
            "檢視或啟動研究、精簡或能力路由 Adaptive Evidence 團隊",
            "研究・簡潔・能力ルーティング型 Adaptive Evidence チームを確認・開始します",
        ),
        "/test" => (
            "Run the configured test executable",
            "執行已設定的測試程式",
            "設定済みのテスト実行ファイルを起動します",
        ),
        "/think" => (
            "Alias for /reasoning",
            "/reasoning 的別名",
            "/reasoning の別名です",
        ),
        "/tools" => (
            "List registered tools and effect classes",
            "列出已註冊工具與副作用類型",
            "登録済みツールと効果区分を一覧表示します",
        ),
        "/trace" => (
            "Control bounded runtime tracing",
            "控制有界執行階段追蹤",
            "上限付き実行トレースを制御します",
        ),
        "/undo" => (
            "Safely undo a verified harness patch",
            "安全復原已驗證的 Harness Patch",
            "検証済み Harness パッチを安全に取り消します",
        ),
        "/vector" => (
            "Configure the global embedding provider and project-local retrieval",
            "設定全域 Embedding Provider 與專案本機檢索",
            "グローバル埋め込み Provider とプロジェクト内検索を設定します",
        ),
        "/why" => (
            "Show auditable decision evidence without private reasoning",
            "顯示可稽核決策證據且不洩漏私有推理",
            "非公開推論を出さず監査可能な判断根拠を表示します",
        ),
        _ => (zh_cn, zh_cn, zh_cn),
    };
    match language {
        UiLanguage::En => en,
        UiLanguage::ZhTw => zh_tw,
        UiLanguage::Ja => ja,
        UiLanguage::ZhCn => zh_cn,
    }
}

const EN: LanguagePack = LanguagePack {
    activity: "Activity",
    input: "Input",
    setup: "Setup",
    setup_cancel_hint: "Esc or /cancel returns to chat",
    command_palette: "Commands",
    command_hint: "↑↓ select · Tab complete · Esc close",
    editor_hint: "←→ move · Home/End · ↑↓ history/commands",
    onboarding_title: "No model is configured. Test models never handle user work.",
    onboarding_step_provider: "Use /provider add for a custom endpoint, or /connect for a built-in provider.",
    onboarding_step_commands: "Type / to browse every command. Use /provider switch and /model to switch routes.",
    model_unconfigured: "Not configured",
    configured_language: "Interface language",
    cancelled: "Setup cancelled",
    provider_add_title: "Custom provider · Responses / Chat Completions / Messages wizard",
    provider_name_prompt: "Provider name (used for future switching)",
    provider_protocol_prompt: "Choose the provider API protocol",
    provider_protocol_responses: "Modern OpenAI protocol · responses endpoint · continuation and reasoning",
    provider_protocol_chat: "Broadly compatible · chat/completions endpoint · most third-party relays",
    provider_protocol_messages: "Claude-compatible protocol · messages endpoint · Anthropic headers",
    provider_url_prompt: "API base URL",
    provider_switch_prompt: "Choose a model provider",
    provider_key_update_prompt: "Choose a provider whose API key should be replaced",
    provider_key_updated: "API key replaced in the OS credential store",
    provider_key_rollback: "New key validation failed; the previous key was restored",
    provider_default_prompt: "Choose the default model",
    vector_setup_title: "Vector setup · global provider and model catalog",
    vector_setup_description: "Providers and keys are global while vector data stays project-local. Voyage and Jina model IDs are built in; every selected model is verified as an embedding model.",
    vector_provider_prompt: "Choose a vector provider",
    vector_custom_name_prompt: "Custom vector provider name (used for future switching)",
    vector_url_prompt: "Embedding API base URL",
    vector_model_prompt: "Embedding model name (manual)",
    vector_models_prompt: "Enter one or more embedding model IDs, separated by commas",
    vector_model_select_prompt: "Choose this provider's embedding model",
    vector_voyage_option: "Built in · API key only · optimized text/code embeddings",
    vector_jina_option: "Built in · API key only · multilingual and code embeddings",
    vector_custom_option: "Named provider · custom URL · multiple model IDs",
    vector_model_verified: "Verified",
    vector_model_verify_on_select: "Verify on selection",
    vector_enabled: "Vector enabled",
    global_configuration: "global configuration",
    vector_dimensions_prompt: "Embedding dimensions (1..65536)",
    vector_dimensions_fallback: "Automatic dimension detection failed; enter a supported dimension manually",
    secure_key_prompt: "API key",
    select_confirm: "↑↓ select · Tab/Enter confirm",
    first_model_hint: "Uses the first catalog model",
    default_model_label: "Default model",
    model_ready: "ready",
    connect_first: "run /connect first",
    choose_as_default: "Set as this provider's default model",
    remove_provider_hint: "Remove the global custom provider and credential reference",
    session_label: "Session",
    goal_label: "Goal",
    model_label: "Model",
    reasoning_label: "Reasoning",
    limits_label: "Limits",
    capability_label: "Capabilities",
    mode_label: "Mode",
    context_label: "Context",
    cache_label: "Cache",
    prompt_cache_label: "Prompt cache",
    agents_label: "Agents",
    provider_switched: "Provider switched",
    provider_verified: "Provider verified and saved",
    models_fetched: "models fetched; choose a default",
    vector_verified: "Vector provider verified",
    dimensions_label: "Dimensions",
    vector_saved_restart: "Saved globally; every project checks health on startup and activates lazily on first semantic request",
    vector_key_saved: "Key saved in the OS credential store; each selected model must pass an embedding response check",
    ready_label: "Ready",
    working_label: "Working",
    secure_label: "Secure input",
    composer_placeholder: "Ask Kernary, or type / to browse commands",
    send_hint: "Enter send · / commands · Ctrl+C cancel",
    scroll_hint: "PgUp/PgDn scroll",
    you_label: "YOU",
    add_provider_action: "Add a Responses, Chat Completions, or Messages endpoint",
    connect_provider_action: "Connect a built-in provider",
    browse_commands_action: "Browse every command",
    exit_hint: "Press Ctrl+C again within 2 seconds to exit",
    vector_label: "Vector",
    vector_configured_label: "configured",
    vector_unconfigured_label: "off",
    vector_ready_label: "ready",
    vector_active_label: "active",
    vector_degraded_label: "degraded",
    vector_setup_action: "Configure the global provider; memory data remains project-local",
    new_session_title: "New project-local session. Start with a focused task.",
    agent_md_action: "Inspect global/project private instructions",
    permission_label: "Permission",
    sandbox_label: "Sandbox",
    permission_cycle_hint: "Shift+Tab permission",
};

const ZH_CN: LanguagePack = LanguagePack {
    activity: "活动",
    input: "输入",
    setup: "设置向导",
    setup_cancel_hint: "Esc 或 /cancel 返回聊天",
    command_palette: "命令",
    command_hint: "↑↓ 选择 · Tab 补全 · Esc 关闭",
    editor_hint: "←→ 移动 · Home/End · ↑↓ 历史/命令",
    onboarding_title: "尚未配置模型；测试模型绝不会处理用户任务。",
    onboarding_step_provider: "自定义中转站使用 /provider add；内置提供商使用 /connect。",
    onboarding_step_commands: "输入 / 浏览全部命令；/provider switch 切换提供商，/model 切换当前模型。",
    model_unconfigured: "未配置",
    configured_language: "界面语言",
    cancelled: "设置已取消",
    provider_add_title: "自定义提供商 · Responses / Chat Completions / Messages 向导",
    provider_name_prompt: "Provider 名称（后续切换使用）",
    provider_protocol_prompt: "选择模型 API 协议",
    provider_protocol_responses: "现代 OpenAI 协议 · /responses · 支持延续与推理参数",
    provider_protocol_chat: "兼容范围最广 · /chat/completions · 常见第三方中转站",
    provider_protocol_messages: "Claude 兼容协议 · /messages · Anthropic 请求头",
    provider_url_prompt: "API Base URL",
    provider_switch_prompt: "选择模型提供商",
    provider_key_update_prompt: "选择要更换 API Key 的模型提供商",
    provider_key_updated: "新 Key 已替换到系统凭据库",
    provider_key_rollback: "新 Key 验证失败；旧 Key 已恢复",
    provider_default_prompt: "选择默认模型",
    vector_setup_title: "向量设置 · 全局 Provider 与模型目录",
    vector_setup_description: "Provider 与 Key 全局复用，向量数据仍按项目隔离；Voyage/Jina 模型 ID 已内置，所选模型必须通过 Embedding 响应验证。",
    vector_provider_prompt: "选择向量模型提供商",
    vector_custom_name_prompt: "自定义向量 Provider 名称（后续切换使用）",
    vector_url_prompt: "Embedding API Base URL",
    vector_model_prompt: "手动输入 Embedding 模型名",
    vector_models_prompt: "输入一个或多个向量模型 ID（逗号分隔）",
    vector_model_select_prompt: "选择该 Provider 的向量模型",
    vector_voyage_option: "内置 · 只需 API Key · 文本与代码向量模型",
    vector_jina_option: "内置 · 只需 API Key · 多语言与代码向量模型",
    vector_custom_option: "自定义名称 · 自定义 URL · 支持多个模型",
    vector_model_verified: "已验证",
    vector_model_verify_on_select: "选择后验证",
    vector_enabled: "向量已启用",
    global_configuration: "全局配置",
    vector_dimensions_prompt: "向量维度（1..65536）",
    vector_dimensions_fallback: "自动检测维度失败，请手动输入该模型支持的维度",
    secure_key_prompt: "API Key",
    select_confirm: "↑↓ 选择 · Tab/Enter 确认",
    first_model_hint: "选择后使用目录中的首个模型",
    default_model_label: "默认模型",
    model_ready: "已连接",
    connect_first: "先运行 /connect",
    choose_as_default: "设为该 Provider 的默认模型",
    remove_provider_hint: "删除全局自定义 Provider 与凭证引用",
    session_label: "会话",
    goal_label: "目标",
    model_label: "模型",
    reasoning_label: "推理",
    limits_label: "限制",
    capability_label: "能力",
    mode_label: "模式",
    context_label: "上下文",
    cache_label: "缓存",
    prompt_cache_label: "提示缓存",
    agents_label: "智能体",
    provider_switched: "已切换提供商",
    provider_verified: "提供商已验证并保存",
    models_fetched: "个模型已获取；请选择默认模型",
    vector_verified: "向量提供商已验证",
    dimensions_label: "维度",
    vector_saved_restart: "已全局保存；每个项目启动时检查健康状态，首次语义请求再惰性激活",
    vector_key_saved: "Key 已进入系统凭证库；每个所选模型都必须通过 Embedding 响应验证",
    ready_label: "就绪",
    working_label: "正在工作",
    secure_label: "安全输入",
    composer_placeholder: "向 Kernary 提问，或输入 / 浏览命令",
    send_hint: "Enter 发送 · / 命令 · Ctrl+C 取消",
    scroll_hint: "PgUp/PgDn 滚动",
    you_label: "你",
    add_provider_action: "添加 Responses、Chat Completions 或 Messages 中转站",
    connect_provider_action: "连接内置模型提供商",
    browse_commands_action: "浏览全部命令",
    exit_hint: "2 秒内再次按 Ctrl+C 退出",
    vector_label: "向量",
    vector_configured_label: "已配置",
    vector_unconfigured_label: "未配置",
    vector_ready_label: "待激活",
    vector_active_label: "已激活",
    vector_degraded_label: "已降级",
    vector_setup_action: "配置全局向量 Provider；记忆数据仍按项目隔离",
    new_session_title: "新的项目本地会话；从一个明确任务开始。",
    agent_md_action: "查看全局/项目私有指令",
    permission_label: "权限",
    sandbox_label: "沙箱",
    permission_cycle_hint: "Shift+Tab 切换权限",
};

const ZH_TW: LanguagePack = LanguagePack {
    activity: "活動",
    input: "輸入",
    setup: "設定精靈",
    setup_cancel_hint: "Esc 或 /cancel 返回聊天",
    command_palette: "命令",
    command_hint: "↑↓ 選擇 · Tab 補全 · Esc 關閉",
    editor_hint: "←→ 移動 · Home/End · ↑↓ 歷史/命令",
    onboarding_title: "尚未設定模型；測試模型絕不會處理使用者任務。",
    onboarding_step_provider: "自訂中轉站使用 /provider add；內建提供商使用 /connect。",
    onboarding_step_commands: "輸入 / 瀏覽全部命令；/provider switch 切換提供商，/model 切換目前模型。",
    model_unconfigured: "未設定",
    configured_language: "介面語言",
    cancelled: "設定已取消",
    provider_add_title: "自訂提供商 · Responses / Chat Completions / Messages 精靈",
    provider_name_prompt: "Provider 名稱（供後續切換使用）",
    provider_protocol_prompt: "選擇模型 API 協議",
    provider_protocol_responses: "現代 OpenAI 協議 · /responses · 支援延續與推理參數",
    provider_protocol_chat: "相容範圍最廣 · /chat/completions · 常見第三方中轉站",
    provider_protocol_messages: "Claude 相容協議 · /messages · Anthropic 請求標頭",
    provider_url_prompt: "API Base URL",
    provider_switch_prompt: "選擇模型提供商",
    provider_key_update_prompt: "選擇要更換 API Key 的模型提供商",
    provider_key_updated: "新 Key 已替換至系統憑證庫",
    provider_key_rollback: "新 Key 驗證失敗；舊 Key 已恢復",
    provider_default_prompt: "選擇預設模型",
    vector_setup_title: "向量設定 · 全域 Provider 與模型目錄",
    vector_setup_description: "Provider 與 Key 全域共用，向量資料仍按專案隔離；已內建 Voyage/Jina 模型 ID，所選模型必須通過 Embedding 回應驗證。",
    vector_provider_prompt: "選擇向量模型提供商",
    vector_custom_name_prompt: "自訂向量 Provider 名稱（供後續切換使用）",
    vector_url_prompt: "Embedding API Base URL",
    vector_model_prompt: "手動輸入 Embedding 模型名稱",
    vector_models_prompt: "輸入一個或多個向量模型 ID（以逗號分隔）",
    vector_model_select_prompt: "選擇此 Provider 的向量模型",
    vector_voyage_option: "內建 · 只需 API Key · 文字與程式碼向量模型",
    vector_jina_option: "內建 · 只需 API Key · 多語言與程式碼向量模型",
    vector_custom_option: "自訂名稱 · 自訂 URL · 支援多個模型",
    vector_model_verified: "已驗證",
    vector_model_verify_on_select: "選擇後驗證",
    vector_enabled: "向量已啟用",
    global_configuration: "全域設定",
    vector_dimensions_prompt: "向量維度（1..65536）",
    vector_dimensions_fallback: "自動偵測維度失敗，請手動輸入模型支援的維度",
    secure_key_prompt: "API Key",
    select_confirm: "↑↓ 選擇 · Tab/Enter 確認",
    first_model_hint: "選擇後使用目錄中的第一個模型",
    default_model_label: "預設模型",
    model_ready: "已連接",
    connect_first: "請先執行 /connect",
    choose_as_default: "設為此提供商的預設模型",
    remove_provider_hint: "刪除全域自訂 Provider 與憑證參照",
    session_label: "工作階段",
    goal_label: "目標",
    model_label: "模型",
    reasoning_label: "推理",
    limits_label: "限制",
    capability_label: "能力",
    mode_label: "模式",
    context_label: "上下文",
    cache_label: "快取",
    prompt_cache_label: "提示快取",
    agents_label: "代理",
    provider_switched: "已切換提供商",
    provider_verified: "提供商已驗證並儲存",
    models_fetched: "個模型已取得；請選擇預設模型",
    vector_verified: "向量提供商已驗證",
    dimensions_label: "維度",
    vector_saved_restart: "已全域儲存；每個專案啟動時檢查健康狀態，首次語意請求時才延遲啟用",
    vector_key_saved: "Key 已進入系統憑證庫；每個所選模型都必須通過 Embedding 回應驗證",
    ready_label: "就緒",
    working_label: "正在工作",
    secure_label: "安全輸入",
    composer_placeholder: "向 Kernary 提問，或輸入 / 瀏覽命令",
    send_hint: "Enter 傳送 · / 命令 · Ctrl+C 取消",
    scroll_hint: "PgUp/PgDn 捲動",
    you_label: "你",
    add_provider_action: "新增 Responses、Chat Completions 或 Messages 中轉站",
    connect_provider_action: "連接內建模型提供商",
    browse_commands_action: "瀏覽全部命令",
    exit_hint: "2 秒內再次按 Ctrl+C 離開",
    vector_label: "向量",
    vector_configured_label: "已設定",
    vector_unconfigured_label: "未設定",
    vector_ready_label: "待啟用",
    vector_active_label: "已啟用",
    vector_degraded_label: "已降級",
    vector_setup_action: "設定全域向量 Provider；記憶資料仍按專案隔離",
    new_session_title: "新的專案本機會話；請從明確任務開始。",
    agent_md_action: "檢視全域/專案私有指令",
    permission_label: "權限",
    sandbox_label: "沙箱",
    permission_cycle_hint: "Shift+Tab 切換權限",
};

const JA: LanguagePack = LanguagePack {
    activity: "アクティビティ",
    input: "入力",
    setup: "セットアップ",
    setup_cancel_hint: "Esc または /cancel でチャットに戻る",
    command_palette: "コマンド",
    command_hint: "↑↓ 選択 · Tab 補完 · Esc 閉じる",
    editor_hint: "←→ 移動 · Home/End · ↑↓ 履歴/コマンド",
    onboarding_title: "モデルが未設定です。テストモデルはユーザーの作業を実行しません。",
    onboarding_step_provider: "独自エンドポイントは /provider add、組み込みプロバイダーは /connect を使います。",
    onboarding_step_commands: "/ で全コマンドを表示し、/provider switch と /model で切り替えます。",
    model_unconfigured: "未設定",
    configured_language: "表示言語",
    cancelled: "セットアップを中止しました",
    provider_add_title: "カスタムプロバイダー · Responses / Chat Completions / Messages 設定",
    provider_name_prompt: "Provider 名（後で切り替えるために使用）",
    provider_protocol_prompt: "モデル API プロトコルを選択",
    provider_protocol_responses: "最新 OpenAI 方式 · /responses · 継続と推論パラメーター",
    provider_protocol_chat: "高い互換性 · /chat/completions · 多くの中継サービス",
    provider_protocol_messages: "Claude 互換 · /messages · Anthropic ヘッダー",
    provider_url_prompt: "API ベース URL",
    provider_switch_prompt: "モデルプロバイダーを選択",
    provider_key_update_prompt: "API キーを更新するプロバイダーを選択",
    provider_key_updated: "新しいキーを OS 資格情報ストアで置き換えました",
    provider_key_rollback: "新しいキーの検証に失敗したため、以前のキーを復元しました",
    provider_default_prompt: "既定モデルを選択",
    vector_setup_title: "ベクトル設定 · グローバル Provider／モデルカタログ",
    vector_setup_description: "Provider とキーは全体で共有し、ベクトルデータはプロジェクト別に保持します。Voyage/Jina のモデル ID は内蔵され、選択モデルは埋め込み応答で検証されます。",
    vector_provider_prompt: "ベクトルモデルのプロバイダーを選択",
    vector_custom_name_prompt: "カスタム Vector Provider 名（後の切り替えに使用）",
    vector_url_prompt: "埋め込み API ベース URL",
    vector_model_prompt: "埋め込みモデル名を手動入力",
    vector_models_prompt: "埋め込みモデル ID をカンマ区切りで1件以上入力",
    vector_model_select_prompt: "この Provider の埋め込みモデルを選択",
    vector_voyage_option: "組み込み · API キーのみ · テキスト／コード埋め込み",
    vector_jina_option: "組み込み · API キーのみ · 多言語／コード埋め込み",
    vector_custom_option: "独自名 · 独自 URL · 複数モデル対応",
    vector_model_verified: "検証済み",
    vector_model_verify_on_select: "選択時に検証",
    vector_enabled: "ベクトルを有効化しました",
    global_configuration: "グローバル設定",
    vector_dimensions_prompt: "ベクトル次元（1..65536）",
    vector_dimensions_fallback: "次元の自動検出に失敗しました。対応する次元を手動入力してください",
    secure_key_prompt: "API キー",
    select_confirm: "↑↓ 選択 · Tab/Enter 確定",
    first_model_hint: "カタログの先頭モデルを使用します",
    default_model_label: "既定モデル",
    model_ready: "接続済み",
    connect_first: "先に /connect を実行してください",
    choose_as_default: "このプロバイダーの既定モデルに設定します",
    remove_provider_hint: "グローバルのカスタム Provider と認証参照を削除します",
    session_label: "セッション",
    goal_label: "ゴール",
    model_label: "モデル",
    reasoning_label: "推論",
    limits_label: "上限",
    capability_label: "機能",
    mode_label: "モード",
    context_label: "コンテキスト",
    cache_label: "キャッシュ",
    prompt_cache_label: "プロンプトキャッシュ",
    agents_label: "エージェント",
    provider_switched: "プロバイダーを切り替えました",
    provider_verified: "プロバイダーを検証して保存しました",
    models_fetched: "件のモデルを取得しました。既定モデルを選択してください",
    vector_verified: "ベクトルプロバイダーを検証しました",
    dimensions_label: "次元数",
    vector_saved_restart: "グローバル保存しました。各プロジェクト起動時に健全性を確認し、最初の意味検索で遅延起動します",
    vector_key_saved: "キーを OS 資格情報ストアへ保存しました。選択モデルごとに埋め込み応答を検証します",
    ready_label: "準備完了",
    working_label: "実行中",
    secure_label: "安全な入力",
    composer_placeholder: "Kernary に質問するか、/ でコマンドを表示",
    send_hint: "Enter 送信 · / コマンド · Ctrl+C 中止",
    scroll_hint: "PgUp/PgDn スクロール",
    you_label: "あなた",
    add_provider_action: "Responses／Chat Completions／Messages エンドポイントを追加",
    connect_provider_action: "組み込みプロバイダーへ接続",
    browse_commands_action: "すべてのコマンドを表示",
    exit_hint: "2 秒以内にもう一度 Ctrl+C を押すと終了します",
    vector_label: "ベクトル",
    vector_configured_label: "設定済み",
    vector_unconfigured_label: "未設定",
    vector_ready_label: "起動待ち",
    vector_active_label: "有効",
    vector_degraded_label: "縮退",
    vector_setup_action: "グローバル Provider を設定し、記憶データはプロジェクト別に保持",
    new_session_title: "新しいプロジェクト専用セッションです。明確なタスクから始めてください。",
    agent_md_action: "グローバル/プロジェクト専用の指示を確認",
    permission_label: "権限",
    sandbox_label: "サンドボックス",
    permission_cycle_hint: "Shift+Tab 権限切替",
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn language_codes_and_packs_are_distinct() {
        for (code, language) in [
            ("en", UiLanguage::En),
            ("zh-CN", UiLanguage::ZhCn),
            ("zh-TW", UiLanguage::ZhTw),
            ("ja", UiLanguage::Ja),
        ] {
            assert_eq!(UiLanguage::parse(code), Some(language));
            assert_eq!(language.code(), code);
            assert!(!language.pack().onboarding_title.is_empty());
        }
        assert_ne!(
            UiLanguage::En.pack().activity,
            UiLanguage::Ja.pack().activity
        );
    }
}
